version: "3"

services:
  postgres:
    container_name: "factory-study"
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=factory-study-db